/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cggmain;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author jdohe
 */
public class GoFishDisplay extends javax.swing.JFrame {

    private GoFish goFishGame;
    private Vector<JLabel> PlayerFaceCard = new Vector<JLabel>();
    private Vector<JLabel> AIFaceCard = new Vector<JLabel>();
    
    /**
     * Creates new form GoFishDisplay
     */
    public GoFishDisplay() {
        initComponents();
        Color CGGGreen = new Color(0, 153, 0);
        GoFishBackground.setBackground(CGGGreen);
        this.setTitle("Card Games Galore - Go Fish");
        this.setSize(1200, 800);
        this.setLocationRelativeTo(null);
        goFishGame = new GoFish();
        this.setVisible(true);
        //PlayerCardA.setLocation(580, 1055);
        //PlayerCardB.setBounds(200, 200, 128, 192);
        //PlayerCardA = new JLabel (new ImageIcon("FaceCards/10.png" ));
        //PlayerCardA.setVisible(true);
        
        // to fill up array, give it all the pictures through a path
        // specify location
        // set visible
        // FaceCard = new (javax.swing.ImageIcon(getClass().getResource("/FaceCards/"+FaceCard+".png")));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GoFishBackground = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        DrawPileDeck = new javax.swing.JLabel();
        PlayerCardA = new javax.swing.JLabel();
        PlayerCardB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GoFishBackground.setBackground(new java.awt.Color(0, 153, 0));
        GoFishBackground.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GoFishBackground.setPreferredSize(new java.awt.Dimension(1480, 720));

        BackButton.setText("BACK TO MAIN MENU");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });

        DrawPileDeck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageResources/Card Games Galore Resources/CardBackResize25.png"))); // NOI18N
        DrawPileDeck.setText("jLabel1");
        DrawPileDeck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DrawPileDeckMouseClicked(evt);
            }
        });

        PlayerCardA.setText("jLabel1");

        PlayerCardB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FaceCards/14.png"))); // NOI18N
        PlayerCardB.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FaceCards/37.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FaceCards/53.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FaceCards/30.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout GoFishBackgroundLayout = new javax.swing.GroupLayout(GoFishBackground);
        GoFishBackground.setLayout(GoFishBackgroundLayout);
        GoFishBackgroundLayout.setHorizontalGroup(
            GoFishBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GoFishBackgroundLayout.createSequentialGroup()
                .addGroup(GoFishBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(GoFishBackgroundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DrawPileDeck, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addComponent(BackButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GoFishBackgroundLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(PlayerCardA, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PlayerCardB, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        GoFishBackgroundLayout.setVerticalGroup(
            GoFishBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GoFishBackgroundLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(GoFishBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackButton)
                    .addComponent(DrawPileDeck, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(GoFishBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayerCardA)
                    .addComponent(PlayerCardB)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GoFishBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GoFishBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        CGGMenuDisplay mainMenu = new CGGMenuDisplay();
        mainMenu.setVisible(true);
    }//GEN-LAST:event_BackButtonMouseClicked

    private void DrawPileDeckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawPileDeckMouseClicked
        // TODO add your handling code here:
        System.out.print("Go fish from the draw pile.");
    }//GEN-LAST:event_DrawPileDeckMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GoFishDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GoFishDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GoFishDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GoFishDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GoFishDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel DrawPileDeck;
    private javax.swing.JPanel GoFishBackground;
    private javax.swing.JLabel PlayerCardA;
    private javax.swing.JLabel PlayerCardB;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
